apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    name: db-noticias
spec:
  containers:
  - name: db-noticias-container
    image: aluracursos/mysql-db:1
    envFrom:
      - configMapRef:
          name: db-configmap
      # - name: MYSQL_ROOT_PASSWORD
        # valueFrom:
        #     configMapKeyRef:
        #       key: db-configmap
        #       name: MYSQL_ROOT_PASSWORD
    ports:
      - containerPort: 3306
